### ISSUE TITLE
Multishot operations

### ISSUE THREAD

**Issue by Noah-Kennedy** [tokio-rs/tokio-uring#104]
io_uring now has multiple multishot operations, including IORING_OP_ACCEPT and IORING_OP_POLL_ADD. We should add support for streaming back completions for such operations.

**Comment by FrankReh** [comment]
Mind suggesting a unit test for the single shot poll_add? I would build off that for the function poll_add itself and then the *multi* version .

**Comment by Noah-Kennedy** [comment]
@FrankReh I think we need to start with asking what the single-shot API should even look like. We can do this as a future, but many multi-shot operations are going to be more useful in the context of us doing something like implementing the (inherently readiness-based) AsyncRead and AsyncWrite APIs, in which case we may need to build something akin to the tokio Registration API at some point.

To be honest, I kinda wanna just try shoving this into a tokio fork. This is hard to do without first forking mio though. Hmm...

**Comment by FrankReh** [comment]
@Noah-Kennedy The single shot and multi shot poll operation (POLL_ADD) could be handy for watching additional urings and tying their file descriptors to the current-thread's default uring. Sounds like glommio does something similar with their secondary uring. I had been wondering how tokio-uring could be expanded to support multiple urings. Perhaps such an ability does not have to built into tokio-uring, per se. A task could build its own uring, somehow, and loop on a poll stream for that uring's file descriptor. Any type of io_uring platform could be used for those extra urings (maybe) since it would be their completion queue status that was being monitored by the primary uring. And that would indicate some designs that tie io_uring functionality with futures should be done independently of the runtime - perhaps something that sits in between the bindings that io-uring provides, and the assumptions that tokio-uring makes.

Still catching up to your idea regarding tokio Registrations...

**Comment by Noah-Kennedy** [comment]
@FrankReh I had been thinking that OP_POLL_ADD would be most effective for compatibility with readiness-based APIs. My thoughts on multi-uring runtimes would be to have a worker per core and to use the inter-ring messaging facilities.

**Comment by FrankReh** [comment]
@Noah-Kennedy Thanks for the feedback.

If it doesn't get in the way of your tokio-uring ideas, I wanted to make it compatible for a small cloud instance too, perhaps a single core or a dual core machine, so keeping everything in a single current-thread was desirable, leaving one core for the application and one for the kernel. And I think multiple rings in one thread comes with some possible advantages like supporting different ring entry sizes (the larger entries used for NVMe command passthroughs) and other per ring optimizations like registered files and registered buffers. But I don't know if multiple rings makes the kernel's work so much harder that the idea that one or two cores could be used efficiently is that important. And I have to look at the buffer or buffers setup for a ring a little more too - but I have thought, like gommio wants to support two levels of latency and throughput, supporting two levels of buffer management could be useful, one where buffers are expected to be freed quickly so they can stay in the cache easily, and one where data may sit for a while while other operations are being awaited without an extra copy - but at the price of the kernel sometimes not finding a buffer to use.

Inter-ring communication is good too but I haven't thought about when it would be used because the idea of zero-copy operations by a single thread is so appealing. Nothing about the design wouldn't allow both I think.

And I almost have my head around tokio Poll and Registration so I can see why that would be important to fit into tokio-uring.

**Comment by FrankReh** [comment]
@Noah-Kennedy How about we use a new issue to track poll_add and multi_poll_add requirements and ideas? I can make a lot of progress on multi_accept alone. 

The io-uring crate has introduced the mechanism of a second set of sq and cq entry sizes, to cope with the kernel's new ability to use urings to pass NVMe commands and results.

I'd like to get a straw man of multi_accept working with both ring sizes.

I'd like to see this crate's lifecycle completion entry, holding just the u32 result right now, can be expanded to hold more info from the completion queue entry, even a VecDeque of results taken from multiple completion queue entries, or if a pair of callbacks is necessary, one for a single completion result and one for a more-coming completion result.

**Comment by Noah-Kennedy** [comment]
@FrankReh that sounds great!

**Comment by FrankReh** [comment]
@Noah-Kennedy FYI I have a first form of accept_multishot working. I would create a PR so you could take a look but it requires a few tweaks to io-uring to make it compile and I have an open question about exposing constants from the sys module.

**Comment by Noah-Kennedy** [comment]
Closing this in favor of #238.
