### ISSUE TITLE
Should File be Send?

### ISSUE THREAD

**Issue by thomasbarrett** [tokio-rs/tokio-uring#229]
I am opening this thread to raise the topic of whether or not the tokio_uring::File type can be made Send. Once a Fd is opened from one thread, there is nothing prevent users from re-using that same Fd on another uring on another thread. Making File !Send is  currently an entirely artificial limitation of tokio-uring.

**Comment by FrankReh** [comment]
I wish you wouldn't use the term artificial. It conveys that the authors didn't give it thought. I think thought was put into it and the decision so far has been to use Rc and RefCell instead of Arc and Mutex to keep things fast and keep the logic around their guards short, with no waiting for locks. I'm not against providing extra functions under the `unsafe` banner.

**Comment by Noah-Kennedy** [comment]
I think it should eventually be made Send, as a part of supporting multi_thread.

**Comment by Noah-Kennedy** [comment]
Closing in favor of #258.
